-- MySQL Script generated by MySQL Workbench
-- Tue Aug  5 13:10:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supramart_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supramart_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supramart_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `supramart_db` ;

-- -----------------------------------------------------
-- Table `supramart_db`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`admin` (
  `admin_id` VARCHAR(6) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`district` (
  `district_id` INT NOT NULL AUTO_INCREMENT,
  `district_name` VARCHAR(45) NULL DEFAULT NULL,
  `province_province_id` INT NOT NULL,
  PRIMARY KEY (`district_id`),
  INDEX `fk_district_province1_idx` (`province_province_id` ASC) VISIBLE,
  CONSTRAINT `fk_district_province1`
    FOREIGN KEY (`province_province_id`)
    REFERENCES `supramart_db`.`province` (`province_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `district_district_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_district1_idx` (`district_district_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_district1`
    FOREIGN KEY (`district_district_id`)
    REFERENCES `supramart_db`.`district` (`district_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`branches` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(45) NULL DEFAULT NULL,
  `City_city_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `fk_branches_City1_idx` (`City_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_branches_City1`
    FOREIGN KEY (`City_city_id`)
    REFERENCES `supramart_db`.`city` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`admin_has_branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`admin_has_branches` (
  `admin_admin_id` VARCHAR(6) NOT NULL,
  `branches_branch_id` INT NOT NULL,
  PRIMARY KEY (`admin_admin_id`, `branches_branch_id`),
  INDEX `fk_admin_has_branches_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  INDEX `fk_admin_has_branches_admin1_idx` (`admin_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_has_branches_admin1`
    FOREIGN KEY (`admin_admin_id`)
    REFERENCES `supramart_db`.`admin` (`admin_id`),
  CONSTRAINT `fk_admin_has_branches_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`bonus_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`bonus_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`bonus` (
  `bonus_id` INT NOT NULL AUTO_INCREMENT,
  `bonus_name` VARCHAR(100) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `role_role_id` INT NOT NULL,
  `bonus_type_type_id` INT NOT NULL,
  `role_role_id1` INT NOT NULL,
  PRIMARY KEY (`bonus_id`),
  INDEX `fk_bonus_bonus_type1_idx` (`bonus_type_type_id` ASC) VISIBLE,
  INDEX `fk_bonus_role1_idx` (`role_role_id1` ASC) VISIBLE,
  CONSTRAINT `fk_bonus_bonus_type1`
    FOREIGN KEY (`bonus_type_type_id`)
    REFERENCES `supramart_db`.`bonus_type` (`type_id`),
  CONSTRAINT `fk_bonus_role1`
    FOREIGN KEY (`role_role_id1`)
    REFERENCES `supramart_db`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`product_categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `stock_quantity` INT NULL DEFAULT '0',
  `reorder_level` INT NULL DEFAULT '10',
  `added_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `supramart_db`.`product_categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(100) NOT NULL,
  `contact_person` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`branches_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`branches_has_products` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `branches_branch_id` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  `suppliers_supplier_id` INT NOT NULL,
  `quantity_change` INT NOT NULL,
  `reasons` VARCHAR(100) NULL DEFAULT NULL,
  `added_date` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_branches_has_products_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_branches_has_products_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  INDEX `fk_branches_has_products_suppliers1_idx` (`suppliers_supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_branches_has_products_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`),
  CONSTRAINT `fk_branches_has_products_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `supramart_db`.`products` (`product_id`),
  CONSTRAINT `fk_branches_has_products_suppliers1`
    FOREIGN KEY (`suppliers_supplier_id`)
    REFERENCES `supramart_db`.`suppliers` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `registered_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `branches_branch_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_customers_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`employee_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`employee_image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`employees` (
  `employee_id` VARCHAR(10) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `mobile_number_1` VARCHAR(15) NOT NULL,
  `mobile_number_2` VARCHAR(10) NULL DEFAULT NULL,
  `hire_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `base_salary` DOUBLE NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_employees_branches1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_employees_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_employees_employee_image1_idx` (`image_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`),
  CONSTRAINT `fk_employees_employee_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `supramart_db`.`employee_image` (`image_id`),
  CONSTRAINT `fk_employees_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `supramart_db`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`employees_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`employees_has_address` (
  `employee_id` VARCHAR(10) NOT NULL,
  `City_city_id` INT NOT NULL,
  `address_line_1` VARCHAR(150) NOT NULL,
  `address_line_2` VARCHAR(150) NULL DEFAULT NULL,
  `postal_code` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`employee_id`, `City_city_id`),
  INDEX `fk_employees_has_City_City1_idx` (`City_city_id` ASC) VISIBLE,
  INDEX `fk_employees_has_City_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_has_City_City1`
    FOREIGN KEY (`City_city_id`)
    REFERENCES `supramart_db`.`city` (`city_id`),
  CONSTRAINT `fk_employees_has_City_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `supramart_db`.`employees` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`month` (
  `month_id` INT NOT NULL AUTO_INCREMENT,
  `month` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`month_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`year` (
  `year_id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`year_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`year_has_month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`year_has_month` (
  `year_id` INT NOT NULL,
  `month_id` INT NOT NULL,
  PRIMARY KEY (`year_id`, `month_id`),
  INDEX `fk_year_has_month_month1_idx` (`month_id` ASC) VISIBLE,
  INDEX `fk_year_has_month_year1_idx` (`year_id` ASC) VISIBLE,
  CONSTRAINT `fk_year_has_month_month1`
    FOREIGN KEY (`month_id`)
    REFERENCES `supramart_db`.`month` (`month_id`),
  CONSTRAINT `fk_year_has_month_year1`
    FOREIGN KEY (`year_id`)
    REFERENCES `supramart_db`.`year` (`year_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`employees_has_salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`employees_has_salary` (
  `salary_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(10) NOT NULL,
  `year_id` INT NOT NULL,
  `month_id` INT NOT NULL,
  `leave_taken` INT NOT NULL,
  `OT_hours` TIME NULL DEFAULT NULL,
  `extra_leave` INT NULL DEFAULT NULL,
  PRIMARY KEY (`salary_id`),
  INDEX `fk_employees_has_year_has_month_year_has_month1_idx` (`year_id` ASC, `month_id` ASC) VISIBLE,
  INDEX `fk_employees_has_year_has_month_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_has_year_has_month_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `supramart_db`.`employees` (`employee_id`),
  CONSTRAINT `fk_employees_has_year_has_month_year_has_month1`
    FOREIGN KEY (`year_id` , `month_id`)
    REFERENCES `supramart_db`.`year_has_month` (`year_id` , `month_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`income` (
  `income_id` INT NOT NULL,
  `year_id` INT NOT NULL,
  `month_id` INT NOT NULL,
  `branches_branch_id` INT NOT NULL,
  `monthly_income` DOUBLE NOT NULL,
  PRIMARY KEY (`income_id`),
  INDEX `fk_income_year_has_month1_idx` (`year_id` ASC, `month_id` ASC) VISIBLE,
  INDEX `fk_income_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_income_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`),
  CONSTRAINT `fk_income_year_has_month1`
    FOREIGN KEY (`year_id` , `month_id`)
    REFERENCES `supramart_db`.`year_has_month` (`year_id` , `month_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`petty_cash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`petty_cash` (
  `petty_cash_id` INT NOT NULL AUTO_INCREMENT,
  `petty_cash_amount` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `year_has_month_year_id` INT NOT NULL,
  `year_has_month_month_id` INT NOT NULL,
  `branches_branch_id` INT NOT NULL,
  PRIMARY KEY (`petty_cash_id`),
  INDEX `fk_petty_cash_year_has_month1_idx` (`year_has_month_year_id` ASC, `year_has_month_month_id` ASC) VISIBLE,
  INDEX `fk_petty_cash_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_petty_cash_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`),
  CONSTRAINT `fk_petty_cash_year_has_month1`
    FOREIGN KEY (`year_has_month_year_id` , `year_has_month_month_id`)
    REFERENCES `supramart_db`.`year_has_month` (`year_id` , `month_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`salary_has_bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`salary_has_bonus` (
  `employees_has_salary_salary_id` INT NOT NULL,
  `bonus_bonus_id` INT NOT NULL,
  PRIMARY KEY (`employees_has_salary_salary_id`, `bonus_bonus_id`),
  INDEX `fk_employees_has_salary_has_bonus_bonus1_idx` (`bonus_bonus_id` ASC) VISIBLE,
  INDEX `fk_employees_has_salary_has_bonus_employees_has_salary1_idx` (`employees_has_salary_salary_id` ASC) VISIBLE,
  CONSTRAINT `fk_salary_has_bonus_bonus1`
    FOREIGN KEY (`bonus_bonus_id`)
    REFERENCES `supramart_db`.`bonus` (`bonus_id`),
  CONSTRAINT `fk_salary_has_bonus_employees_has_salary1`
    FOREIGN KEY (`employees_has_salary_salary_id`)
    REFERENCES `supramart_db`.`employees_has_salary` (`salary_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`sales` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `payment_method` VARCHAR(50) NULL DEFAULT NULL,
  `sale_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `branches_branch_id` INT NOT NULL,
  `employee_id` VARCHAR(10) NOT NULL,
  `customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sales_branches1_idx` (`branches_branch_id` ASC) VISIBLE,
  INDEX `fk_sales_employees1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_sales_customers1_idx` (`customers_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_branches1`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `supramart_db`.`branches` (`branch_id`),
  CONSTRAINT `fk_sales_customers1`
    FOREIGN KEY (`customers_customer_id`)
    REFERENCES `supramart_db`.`customers` (`customer_id`),
  CONSTRAINT `fk_sales_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `supramart_db`.`employees` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`sale_items` (
  `sale_item_id` INT NOT NULL AUTO_INCREMENT,
  `sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sale_item_id`),
  INDEX `sale_id` (`sale_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `sale_items_ibfk_1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `supramart_db`.`sales` (`sale_id`)
    ON DELETE CASCADE,
  CONSTRAINT `sale_items_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `supramart_db`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supramart_db`.`suppliers_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supramart_db`.`suppliers_has_address` (
  `supplier_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `address_line_1` VARCHAR(150) NOT NULL,
  `address_line_2` VARCHAR(150) NOT NULL,
  `postal_code` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`supplier_id`, `city_id`),
  INDEX `fk_suppliers_has_city_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_suppliers_has_city_suppliers1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_suppliers_has_city_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `supramart_db`.`city` (`city_id`),
  CONSTRAINT `fk_suppliers_has_city_suppliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `supramart_db`.`suppliers` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
